#!/bin/bash
#
#Andmebaasi loomise skript
kasutaja=$1
parool=$(tr -cd '[:alnum:]' < /dev/urandom | fold -w30 | head -n1)
echo "$password=$parool" > .parrol.tmp
echo "$parool" > .parool2.tmp

if [ $# -ne 1 ]; then
	echo "Kasutusjuhend: $0 Kasutajanimi"
elif [ ! -e /home/$kasutaja/.my.cnf ]; then

	echo "Teie kodukataloogist puudub andmebaasi konfiguratsioonifail!"
	echo "Konfiguratsioonifaili loomine."
	echo "Palun sisestage Andmebaasi root kasutaja parool: "
	read dbrootpass

	################################################
	echo "[Client]" > /home/$kasutaja/.my.cnf
	echo "User=$kasutaja" >> /home/$kasutaja/.my.cnf
	paste .parool.tmp >> /home/$kasutaja/.my.cnf
	################################################

	echo "sisesta andmebaasi nimi"
	read dbnimi
	dbname="$kasutaja""_""$dbnimi"
	for dbpass in $(cat .parool2.tmp)
	do
	mysql -uroot -p$dbrootpass -e "CREATE DATABASE $dbname ; GRANT ALL PRIVILEGES ON $dbname.* TO $kasutaja@localhost IDENTIFIED BY '$dbpass'"
	done
	echo "Andmebaas on loodud."

chown "$kasutaja"":""$kasutaja" /home/$kasutaja/.my.cnf
chmod 0644 /home/$kasutaja/.my.cnf
rm .parool.tmp
rm.parool2.tmp
else
	echo "Sisesta andmebaasi nimi"
	read dbnimi
	dbname="$kasutaja""_""$dbnimi"

	for dbpass in $(cat .parool2.tmp)
	do
	mysql -uroot -p$dbrootpass -e "CREATE DATABASE $dbname ; GRANT ALL PRIVILEGES TO $kasutaja@localhost INDETIFIED BY '$dbpass'"
	done
	echo "Andmebaas on loodud."

chown "$kasutaja"":""$kasutaja" /home/$kasutaja/.my.cnf
chmod 0644 /home/$kasutaja/.my.cnf
rm .parool.tmp
rm .parool2.tmp
fi
