#!/bin/bash
#pwgen -s 8 1

while read nimi
do
	kasutaja=$nimi
	parool=$(pwgen 6)
		echo "$kasutaja parool on $parool"
	useradd -m -s /bin/bash  $kasutaja
		echo "$kasutaja:$parool" | chpasswd
		echo "$kasutaja:$parool" >> $gen_paooliga_kasutajad
done < $1
