#!/bin/bash
#
#kasutajate lisamise skript
if [ $# -ne 1 ]; then
	echo "Kasutajajuhend: $0 failinimi" 
else 
		failinimi=$1
	if [ -f $failinimi -a -r $failinimi ]; then
		echo "fail on korras"
		for nimi in $(cat $failinimi)
		do
			#faili sisu nimi on nähtav, nüüd tuleb echo asendada vajaliku skriptiga
			# echo $rida
			sh lisa_kasutaja $nimi 
			#sellega läheb tööle lisa_kasutaja skript
		done
	else
		echo "probleem failiga $failinimi"
	fi	
#parameetrite kontrolli lõpp
fi
