#!/bin/bash
#pwgen -s 8 1
File= "gen_parooliga_kasutajad"
failnimi=$1

While IFS read line; do
i=$(( i + 1 ))
pass=$(pwgen -s 8 1)
useradd -m -s /bin/bash $line
echo "$line:$pass" | chpasswd
echo "$line:$pass" >> $file
done < $failinimi
